### ISSUE TITLE
Dockerized wdb server doesn't react to SIGTERM

### ISSUE THREAD

**Issue by yajo** [Kozea/wdb#136]
I use wdb-server in a `docker-compose.yml` file, and when stopping services, it's always the latest. I investigated, and it seems it doesn't react to `SIGTERM`:

![Peek 18-11-2019 09-09](https://user-images.githubusercontent.com/973709/69039389-beb54b80-09e3-11ea-9bfa-ada7a2c13693.gif)

**Comment by yajo** [comment]
I finally found a good workaorund:

```yaml
  wdb:
    image: kozea/wdb
    # HACK https://github.com/Kozea/wdb/issues/136
    init: true
```

This avoids the problem of `wdb.server.py` process stuck when powering off the computer.
